### ISSUE TITLE
Subscription objects returned by `await await stripe.subscriptions.list()` don't match `Stripe.Subscription` type interface

### ISSUE THREAD

**Issue by pirate** [stripe/stripe-node#1091]
I'm using `stripe-node` `v8.128.0` (and pinned the API version to `2020-08-27`) with Typescript in `strict: true` mode, and `tsc` `v4.1.2`.

I'm trying to process the list of subscriptions returned by the [`stripe.subscriptions.list()` call](https://github.com/stripe/stripe-node/blob/master/types/2020-08-27/Subscriptions.d.ts#L1089), but I'm struggling because the entries in the returned `ApiListPromise<Stripe.Subscription>` don't actually match the schema of the [`Stripe.Subscription` inteface](https://github.com/stripe/stripe-node/blob/master/types/2020-08-27/Subscriptions.d.ts#L8).

```typescript
import Stripe from 'stripe'

const stripe = new Stripe(
	process.env.STRIPE_SECRET_KEY as string,
	{apiVersion: '2020-08-27'},
)

const STRIPE_PAGE_LIMIT = 100
let tail_item: string | null = null

const all_subscriptions: []
do {
    const page: Stripe.ApiList<Stripe.Subscription> = await stripe.subscriptions.list({
        status: 'active',
        limit: STRIPE_PAGE_LIMIT,
        ...(tail_item ? {starting_after: tail_item} : {}),
    } as Stripe.SubscriptionListParams)

    page.data.forEach((entry: Stripe.Subscription) => {
        console.log({
            user_id: entry.customer,
            plan_id: entry.plan.id,
            amt: entry.plan.amount,
            unit: entry.plan.currency,
        })
    })

    if (page.data.length === STRIPE_PAGE_LIMIT) {
        tail_item = page.data[page.data.length-1].id
    } else {
        tail_item = null
    }
} while (tail_item)
```

This is failing because `Stripe.Subscription` doesn't have a `plan` key (among other missing keys):
```typescript
stripe.ts:40:35 - error TS2339: Property 'plan' does not exist on type 'Subscription'.

40                 plan_id: entry.plan.id,
                                  ~~~~
```

---

Here is the relevant function signature provided by `stripe-node` `2020-08-27` showing the return type entries should be `Stripe.Subscription`:  
https://github.com/stripe/stripe-node/blob/master/types/2020-08-27/Subscriptions.d.ts#L1089
```typescript
      list(
        params?: SubscriptionListParams,
        options?: RequestOptions
      ): ApiListPromise<Stripe.Subscription>;
      list(options?: RequestOptions): ApiListPromise<Stripe.Subscription>;
```

And here is an actual subscription entry in `(await stripe.subscriptions.list()).data[0]` which doesn't match `Stripe.Subscription`:
(see the `plan` key is present on line 36, among other differences):
```javascript=
{
  id: 'sub_somerandomidhere',
  object: 'subscription',
  application_fee_percent: null,
  billing_cycle_anchor: 1608022098,
  billing_thresholds: null,
  cancel_at: null,
  cancel_at_period_end: false,
  canceled_at: null,
  collection_method: 'charge_automatically',
  created: 1608022098,
  current_period_end: 1610700498,
  current_period_start: 1608022098,
  customer: 'cus_abadsfkjljwer234',
  days_until_due: null,
  default_payment_method: null,
  default_source: null,
  default_tax_rates: [],
  discount: null,
  ended_at: null,
  items: {
    object: 'list',
    data: [ [Object] ],
    has_more: false,
    total_count: 1,
    url: '/v1/subscription_items?subscription=sub_somerandomidhere'
  },
  latest_invoice: 'in_adbaerredacted',
  livemode: true,
  metadata: {},
  next_pending_invoice_item_invoice: null,
  pause_collection: null,
  pending_invoice_item_interval: null,
  pending_setup_intent: null,
  pending_update: null,
  plan: {
    id: 'plan_abacdsf2342341',
    object: 'plan',
    active: true,
    aggregate_usage: null,
    amount: 0,
    amount_decimal: '0',
    billing_scheme: 'per_unit',
    created: 1588778184,
    currency: 'usd',
    interval: 'month',
    interval_count: 1,
    livemode: true,
    metadata: {},
    nickname: 'abaasfwer2342-0',
    product: 'prod_asdlflkjlk2324',
    tiers_mode: null,
    transform_usage: null,
    trial_period_days: null,
    usage_type: 'licensed'
  },
  quantity: 1,
  schedule: null,
  start_date: 1608022098,
  status: 'active',
  transfer_data: null,
  trial_end: null,
  trial_start: null
}
```

In general this object does not seem to match the `Stripe.Subscription` interface. Is there a different type/interface I should be using for these returned objects instead? Or are the types out-of-date from the API and need to be updated?

Thanks for any help!

**Comment by remi-stripe** [comment]
The Typescript definitions in stripe-node are for the latest API version we published which is `2020-08-27`. The library itself does support any API version today though. Your code is likely not pinned to the latest API version so it's using whatever is the default on your account which could have a different shape. You can explicitly force the version to the latest as documented here: https://stripe.com/docs/api/versioning?lang=node

If you do this in your code where you initialize stripe-node, every call will use the latest API version (and ignore the one set on your account) and the returned values will match what you have in the types.

**Comment by pirate** [comment]
Just tried that, force-set the API version to `2020-08-27`. the schema returned is still the same and still does not comply with the `Stripe.Subscription` interface.

**Comment by remi-stripe** [comment]
@pirate Sorry that's correct, it won't be exactly the same, because there will always be extra properties. Just you are not supposed to access `plan` or `quantity` top-level. Those are here only for legacy reasons, and the types in stripe-node correspond to the canonical integration paths that we recommend. You should access the plan details directly from within the `items` sub-list so `items.data[0].price.id` is where you would access that information.

If you absolutely want to use `plan` top-level (though you  should not for new code) you will have to disable Typescript signature verification(s) for those lines of code.

**Comment by pirate** [comment]
Ah ok, that explains it, thanks.
