### ISSUE TITLE
Webhook signature verification and bodyParser.json issue

### ISSUE THREAD

**Issue by manu-silicon** [stripe/stripe-node#341]
If you use in your express app `bodyParser.json()` for all routes, and then have a dedicated route for stripe's webhook, then the second call to `bodyParser.json({verify:  ...})` as done in the example has no effect.

I have the following code:
```
app.use(bodyParser.json());
...
app.use('/stripeUrl', stripeRoute);
app.use('/user', userRoute);
....
```

The **StripeRoute** is defined exactly as the example. 

Unfortunately it doesn't work. Only if I comment out the first call to `bodyParser.json` does it work. Which mean that I cannot have a call to `bodyParser` just for my route, I need to add the `verify` function my top call to `bodyParser.json` and to avoid having to pay for the conversion all the time check for the Url to match my stripe route.

Maybe the doc should reflect that, and if it is supposed to work then some guidance as it doesn't for me.

Thanks!

**Comment by brandur-stripe** [comment]
@jlomas-stripe Would you mind providing some guidance/advice on this one? Thanks!

**Comment by ronzeidman** [comment]
This is the way I'm handling it:
```ts
// main file
app
    .set(...)
    .use(...<helmet, cors, compression, logging...>)
    .use('/stripe-webhooks', stripeWebhookRoutes) //the webhooks must come before the default json body parser
    .use(bodyParser,json())

// webhook handling file

export const stripeWebhookRoutes = Router()
    .use(bodyParser.raw({type: '*/*'}))
    .post('', eventParser(process.env.STRIPE_WEBHOOK_SECRET), mainStripeWebhook)
    .post('/connect', eventParser(process.env.STRIPE_WEBHOOK_CONNECT_SECRET), connectStripeWebhook);

function eventParser(secret) {
    return (req, res, next) => {
        try {
            req.body = stripe.webhooks.constructEvent(
                req.body.toString(),
                req.headers['stripe-signature'],
                secret);
        } catch (error) {
            return res.sendStatus(httpStatus.BAD_REQUEST);
        }
        return next();
    }
}
```

**Comment by manu-silicon** [comment]
@ronzeidman Thanks for sharing your solution, mine is:

```
app.use(bodyParser.json({
    // Because Stripe needs the raw body, we compute it but only when hitting the Stripe callback URL.
    verify: function(req,res,buf) {
        var url = req.originalUrl;
        if (url.startsWith('/stripe-webhooks')) {
            req.rawBody = buf.toString()
        }
    }}));
```

At the end it does what we need but I think it should be provided in the doc as currently you might think that the example would be easily plug-able as is but it is not.

**Comment by jlomas-stripe** [comment]
This is a really good point, but I think it's going to be pretty specific to how your application is implemented.

I guess there are a number of different ways this could be implemented; the idea of the documentation example was just to provide a way to get it working quickly.

**Comment by manu-silicon** [comment]
It might be good to highlight this in the example that proper care has to be done for the bodyParser. Especially in the official docs at https://stripe.com/docs/webhooks where there is no mention on how to set this up, and I think the following comment:
```
// We use a router here so it can use its own `bodyParser` instance to add
// the raw POST data to the `request`
```
is actually confusing making you believe that it will work all the time because it is in its own route.

**Comment by lincolnthree** [comment]
Yep. I ran into this too. Still not sure how I want to handle it.

**Comment by floatingLomas** [comment]
Those docs were based on [my example](https://github.com/stripe/stripe-node/blob/master/examples/webhook-signing/express.js) so ... this is my bad.

I'll take a look and see if there's another/better/easier/more-consistent way to get at the raw body in Express without using `body-parser`.

**Comment by jlomas-stripe** [comment]
Ok, so you can accomplish the same with just simple middleware:

```
function addRawBody(req, res, next) {
  req.setEncoding('utf8');

  var data = '';

  req.on('data', function(chunk) {
    data += chunk;
  });

  req.on('end', function() {
    req.rawBody = data;

    next();
  });
}
```

**Comment by joaoreynolds** [comment]
I'm pulling my hair out and could really use some insight. I've tried all methods mentioned above (using bodyParser.raw, using the `addRawBody` middleware).

Note: this is an event for a connected account, I need to handle the `account.application.deauthorized` event. Not sure if the fact that it's a connected account has anything to do with it.

I'm using the latest stripe package `v4.24.0`

Here's my first middleware/route handler (no other middleware above this):
```javascript
app.post('/stripe-webhooks', bodyParser.raw({type: '*/*'}), postStripeWebhooks)
//...further down I do the standard, json parser (but even if I remove that it makes not difference)
app.use(bodyParser.json())
```

And `postStripeWebhooks`:
```javascript
const body = req.body.toString()
try {
  const event = stripe.webhooks.constructEvent(body, req.headers['stripe-signature'], config.stripeWebhookSecret)
  console.log(event)
}
catch(e) {
  console.log('Error', e.message)
}
```

Every way I go about it I get the same result: `No signatures found matching the expected signature for payload` I've also tried everything from the example at https://github.com/stripe/stripe-node/blob/master/examples/webhook-signing/express.js Please help!

**Comment by jlomas-stripe** [comment]
@joaoreynolds If you use the 'simple middleware' from the example, and use `request.rawBody` (instead of `req.body.toString()`), does that work?

**Comment by joaoreynolds** [comment]
*epic facepalm

I just thought, "know what? I better check my webhook secret key even though I'm sure I have that set".

#### I had the wrong effing webhook secret key stored in my production environment variables!

(That moment when you realize you're a terrible developer and nobody should hire you, haha)

Thanks @jlomas-stripe for being willing to help.

In an effort to be somewhat productive to this thread, after cleaning my code, I found that @manu-st 's version was the least-invasive to my app, allowing me to use `bodyParser.json()` on the rest of my app.

**Comment by jlomas-stripe** [comment]
You're very welcome - any time! :)

**Comment by Ontokrat** [comment]
My implementation in Meteor - thanks to @manu-st.
I use [Picker](https://github.com/meteorhacks/picker) as router Server Side ([allow filter and sub-routes](https://github.com/meteorhacks/picker#filtering-and-sub-routes)).
Body-parser in JSON for every webhook / exception for Stripe: verification of webhook's signature (raw) and then handling the same webhook in JSON.

```
import bodyParser from 'body-parser';
import { Picker } from 'meteor/meteorhacks:picker';

// Middleware declaration
Picker.middleware(bodyParser.json({
  limit: '10MB',
  verify: function(req,res,buf) {
    var url = req.originalUrl;
    if (url.startsWith('/stripe-webhooks')) {
      req.rawBody = buf.toString()
    }
  }
}));

// filtered main route
var postRoutes = Picker.filter(function(req, res, buf) {
  var url = req.originalUrl;
  if (url.startsWith(/stripe-webhooks')) {
    // verify webhook's signature if he comes from stripe
    // 'req.rawBody' available here
    // Got only 'empty constructEvent' from official library: let event = stripe.webhooks.constructEvent(req.body, sig, endpointSecret);
    // adapt here https://github.com/stripe/stripe-node/blob/master/lib/Webhooks.js
    // see details: https://stripe.com/docs/webhooks#verify-manually
  }
    // handle only POST requests
    return req.method == "POST"
});


// from route, handling webhook and sending request
postRoutes.route('url', (request, response) => {
  // handle result here
});
```

**Comment by lomegg** [comment]
The issue is still present and driving me mad.

**Comment by floatingLomas** [comment]
@lomegg Can you provide more details on your issue and the specifics of your implementation, ie versions, where/how you're running it?

**Comment by lomegg** [comment]
@floatingLomas I am running it with express when getting a webhook after the simple cart charge (those are not required but I use them as confirmation in my eCommerce, so I need them to be signature verified). My issue is that I am getting object instead of json even after I use bodyParser as middleware like this  
`var rawParser  = bodyParser.raw({type: "*/*"});`
`app.all('/webhook', rawParser, keystone.middleware.api, routes.api.webhook.process);`

Note that `verify` option in bodyParser doesn't get called if I assign function to it.
No matter how I try, I can't get webhook request body in any form other than javascript object.
And if I convert that object to json, I'm getting validation error because it's not pure request body.

**Comment by jlomas-stripe** [comment]
@lomegg What does `keystone.middleware.api` do?  Does that overwrite the `body` by chance?

**Comment by lomegg** [comment]
@jlomas-stripe It provides some api methods, I was testing with it switched off to the same effect. But I will double check on that again, thanks

**Comment by dorelljames** [comment]
Here's how I solved mine here. The arrangement here is pretty important.

```javascript
app.use(bodyParser.raw({type: "*/*"})); // this goes top above .json below
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
```

Hope that helps someone who also stumbles here. Good luck!

**Comment by floatingLomas** [comment]
Best bet is to share the code in `routes.api.webhook.process` here, or probably better, with Support: https://support.stripe.com/email

**Comment by nabilfreeman** [comment]
Thanks @manu-st for such an elegant solution.

It meant that we didn't have to refactor our Express routing. Great job!

**Comment by pincheira** [comment]
@manu-st 's solution is what I got it working with. The thing is that most people's express setup is doing:

```javascript
app.use(bodyParser.json());
```

which sets the json parser for all body objects by default. So I just now pass a setup object to it that includes the block that @manu-st showed.

```javascript
app.use(bodyParser.json(setupForStripeWebhooks));
```

That object being:

```javascript
const setupForStripeWebhooks = {
  // Because Stripe needs the raw body, we compute it but only when hitting the Stripe callback URL.
  verify: function (req, res, buf) {
    var url = req.originalUrl;
    if (url.startsWith('/webhooks/stripe')) {
      req.rawBody = buf.toString();
    }
  }
};

**Comment by karlr-stripe** [comment]
(posting this for visibility for people who find this through search engines) If you use [express-generator](https://expressjs.com/en/starter/generator.html) to create your project, it will likely add the `app.use(express.json());` [line](https://github.com/expressjs/generator/blob/master/bin/express-cli.js#L172) to your app.js which also sets the JSON parser on all request bodies by default. So that is another thing to watch out for!

**Comment by wdmtech** [comment]
For those travelling seeking solutions for [Feathers.js](https://feathersjs.com) (like I was) check out [feathers-stripe-webhooks](https://github.com/fixate/feathers-stripe-webhooks) which will do all this for you 👍

**Comment by DanielGibbsNZ** [comment]
> For those seeking solutions for [Feathers.js](https://feathersjs.com) (like I was) check out [feathers-stripe-webhooks](https://github.com/fixate/feathers-stripe-webhooks) which will do all this for you 👍

Unfortunately this does not seem to be the case. I get the same problem even when using `feathers-stripe-webhooks`.

**Comment by stevus** [comment]
Why do these issues keep getting closed? Feels like there's a big issue with the signature validation code around needing the raw body. I am also having this problem but hard to find a solution when every issue gets diagnosed as user error.

**Comment by jlomas-stripe** [comment]
This isn't a `stripe-node` problem, it's a problem with your web framework, or the way you've configured it or are using it - there isn't really much we can do here unfortunately.

In order to calculate the signature, `stripe-node` needs the _exact, complete raw text body_ as received by your application; if your framework doesn't handle making that available because it's parsed/altered it in some way, then this won't work for you - unless you can find a workaround, and that workaround is going to be very specific to your application, because it will depend on how your application is configured/what it does/how it does what it does.

**Comment by stevus** [comment]
@jlomas-stripe it might indeed be a framework issue, but the way the Stripe node package requires a raw payload doesn't fit too well with some well established patterns for body-parsing etc. It just feels like this implementation only works with hobby or quick-hack builds where the POST handler is right at the Express app root where only a body parser is used. 

If you have a solution that works well with an Express Router where body parsers can be switched out ad-hoc, I think that would solve a lot of these issues.

**Comment by ob-stripe** [comment]
@stevus I don't think that's specific to Stripe -- all implementations of webhook signatures I'm aware of rely on a MAC or digital signature that uses the raw payload. I understand this is a common pain point for Node users, but as @jlomas-stripe said above I'm not sure there's much more we can do to help with this.

@SamMatthewsIsACommonName There's no reason why signature verification would fail or succeed depending on the event's type -- the signature is computed and verified using the raw payload and is not even aware that the payload is a JSON string. If you can give more information about how your webhook handler is set up, we might be able to help you debug this issue. I also recommend you reach out to Stripe's support at https://support.stripe.com/email if you haven't already.

**Comment by SamMatthewsIsACommonName** [comment]
@ob-stripe reason or not this is what happens, I'm purely going off of what is happening:

<img width="1240" alt="screen shot 2018-11-23 at 11 11 10 am" src="https://user-images.githubusercontent.com/21329063/48952553-99951680-ef10-11e8-98d9-3567a3787a63.png">
<img width="1237" alt="screen shot 2018-11-23 at 11 11 27 am" src="https://user-images.githubusercontent.com/21329063/48952554-99951680-ef10-11e8-96b4-b2df8975c9e3.png">

The handler is set up as per the docs but uses req.rawBody as per firebase cloud functions spec.
I don't understand why if it was set up wrong at all it would work 50% of time and not work other 50%?

**Comment by ob-stripe** [comment]
Sorry, I wasn't trying to imply that you were wrong and the issue you're describing wasn't happening, merely that it _shouldn't_ be happening.

I think Firebase's `rawBody` returns a Buffer instance. Can you try converting it to a string? E.g. with `req.rawBody.toString('utf8')`

**Comment by SamMatthewsIsACommonName** [comment]
Ok great thanks, I thought the battle was won finding the right way to get the rawBody haha. Thanks!

**Comment by ob-stripe** [comment]
@SamMatthewsIsACommonName We just released stripe-node 6.15.1 which should let you pass `Buffer` instances to `Webhook.constructEvent()` without having to manually convert them to strings yourself. Thanks for reporting this, hopefully this makes the library a bit easier to use for you and other Firebase users!

**Comment by SamMatthewsIsACommonName** [comment]
Great thanks!

**Comment by SamMatthewsIsACommonName** [comment]
Ok after monitoring a while, the error is still happening (with latest release 6.15.1).
I included a log check of:
````
   console.log('rawBody is buffer: ', Buffer.isBuffer(req.rawBody));
````

And this is what you're seeing in the screen shots. So it's correctly identifying it as a buffer for both the ones that work (most of them) and the ones that don't(some of them), however the toString doesn't seem to be solving the issue for all

<img width="1248" alt="screen shot 2018-11-25 at 11 34 05 pm" src="https://user-images.githubusercontent.com/21329063/48993313-fe1bc580-f10a-11e8-96b8-0691c66dd5e0.png">

**Comment by ob-stripe** [comment]
@SamMatthewsIsACommonName Argh :/ Can you try adding some code to manually extract the event IDs in case the signature verification fails (something like `JSON.parse(req.rawBody).id` should work), and reach out to support at https://support.stripe.com/email with some of those event IDs as well as their respective `Stripe-Signature` headers? Hopefully we can figure out what these events have in common and causes the signature verification to fail.

**Comment by SamMatthewsIsACommonName** [comment]
@ob-stripe will do. I'll start writing each fail to the database with the headers and ids. It does seem to be related to events weirdly because they come in bursts of all failing at once or all passing... So it's like there is some time where stripe sends a lot of events of some type every day. Anyway I'll log them all to database as you suggest. Thanks

**Comment by lomegg** [comment]
> @ob-stripe will do. I'll start writing each fail to the database with the headers and ids. It does seem to be related to events weirdly because they come in bursts of all failing at once or all passing... So it's like there is some time where stripe sends a lot of events of some type every day. Anyway I'll log them all to database as you suggest. Thanks

Sounds like some async process mutating the body and sometimes it's being slower than stripe check

**Comment by SamMatthewsIsACommonName** [comment]
Oh wow, ok I've found the issue. The ones that are failing are coming from test data... I'm so sorry! It was still enabled and hitting the endpoint with events from test accounts etc... So sorry for the time wasting!

**Comment by ob-stripe** [comment]
@SamMatthewsIsACommonName No worries! Glad you figured it out and thanks for letting us know :)

**Comment by mebibou** [comment]
What about allowing json in `constructEvent`? wouldn't it just solve everyone's problems?

**Comment by ob-stripe** [comment]
@mebibou No, the signature verification needs the raw body as a text string. Reserializing already deserialized JSON back into a text string doesn't work as the resulting string might be different (key order is not guaranteed, indentation might be different, etc.).

**Comment by kurry421** [comment]
for anyone still struggling... this is what worked for me. 
```
...
var app = express();
//This is specific raw body for /webhooks/stripe route 
app.use('/webhooks/stripe', bodyParser.raw({type: "*/*"}))
//This is normal body parsing for everything else
app.use(bodyParser.json());


...
//later on..

const stripe = require('stripe')('sk_..');
const endpointSecret = 'whsec...';

app.post('/webhooks/stripe', (request, response) => {
  const sig = request.headers['stripe-signature'];
  let event;
  try {
    event = stripe.webhooks.constructEvent(request.body, sig, endpointSecret);
  } catch (err) {
    return response.status(400).send(`Webhook Error: ${err.message}`);
  }

  // Handle the checkout.session.completed event
  if (event.type === 'checkout.session.completed') {
    const session = event.data.object;
  
    //Complete function here ...
  }

  // Return a response to acknowledge receipt of the event
  response.json({received: true});
});
```

**Comment by danlupascu** [comment]
> for anyone still struggling... this is what worked for me.
> 
> ```
> ...
> var app = express();
> //This is specific raw body for /webhooks/stripe route 
> app.use('/webhooks/stripe', bodyParser.raw({type: "*/*"}))
> //This is normal body parsing for everything else
> app.use(bodyParser.json());
> 
> 
> ...
> //later on..
> 
> const stripe = require('stripe')('sk_..');
> const endpointSecret = 'whsec...';
> 
> app.post('/webhooks/stripe', (request, response) => {
>   const sig = request.headers['stripe-signature'];
>   let event;
>   try {
>     event = stripe.webhooks.constructEvent(request.body, sig, endpointSecret);
>   } catch (err) {
>     return response.status(400).send(`Webhook Error: ${err.message}`);
>   }
> 
>   // Handle the checkout.session.completed event
>   if (event.type === 'checkout.session.completed') {
>     const session = event.data.object;
>   
>     //Complete function here ...
>   }
> 
>   // Return a response to acknowledge receipt of the event
>   response.json({received: true});
> });
> ```

this worked great for me! Thank you!!

**Comment by filipbarak** [comment]
> for anyone still struggling... this is what worked for me.
> 
> ```
> ...
> var app = express();
> //This is specific raw body for /webhooks/stripe route 
> app.use('/webhooks/stripe', bodyParser.raw({type: "*/*"}))
> //This is normal body parsing for everything else
> app.use(bodyParser.json());
> 
> 
> ...
> //later on..
> 
> const stripe = require('stripe')('sk_..');
> const endpointSecret = 'whsec...';
> 
> app.post('/webhooks/stripe', (request, response) => {
>   const sig = request.headers['stripe-signature'];
>   let event;
>   try {
>     event = stripe.webhooks.constructEvent(request.body, sig, endpointSecret);
>   } catch (err) {
>     return response.status(400).send(`Webhook Error: ${err.message}`);
>   }
> 
>   // Handle the checkout.session.completed event
>   if (event.type === 'checkout.session.completed') {
>     const session = event.data.object;
>   
>     //Complete function here ...
>   }
> 
>   // Return a response to acknowledge receipt of the event
>   response.json({received: true});
> });
> ```

weirdly worked for me even though it's very similar to all that I've tried before!

Thanks!

**Comment by joshbedo** [comment]
How do you fix this I seriously have wasted so much time with examples and trying different things but can't fix this error. I have a Firebase cloud function running an express API and I'm trying

```
app.use('/webhook', bodyParser.raw({type: "*/*"}));
app.use(bodyParser.json());
```

but I'm still getting the same error...

**Comment by pincheira** [comment]
@joshbedo I guess the `bodyParser` needs to be set before.

I do it like this:

```

  const setupForStripeWebhooks = {
    // Because Stripe needs the raw body, we compute it but only when hitting the Stripe callback URL.
    verify: function (req, res, buf) {
      var url = req.originalUrl;
      if (url.startsWith('/webhooks/stripe')) {
        req.rawBody = buf.toString();
      }
    }
  };
  app.use(bodyParser.json(setupForStripeWebhooks));

```

I hope this snippet can help.

**Comment by xaphod** [comment]
Frustrating to lose 30 minutes because the code example on https://stripe.com/docs/webhooks/signatures -> **Verifying signatures using our official libraries** is incorrect -- using that code verbatim (with nothing else in the chain, ie. fresh express app) throws this error. I too had to use the req.rawBody approach.

Stripe, you should update that code in that doc, as it does not work using today's express / body-parser.

**Comment by cjavilla-stripe** [comment]
Hey @xaphod can you share how you setup express? I just tried this from scratch and the demo code worked fine.

What errors are you seeing? The key here is that the request body must be the most raw request body string not deserialized to a json object. If body parser is being setup globally to convert json requests to json objects, then adding the middleware in the express route directly doesn't work afaik and instead you need to use the trick from @pincheira where you only apply the raw body for the webhook route and deserialize the rest.

https://www.youtube.com/watch?v=tjH4GRbsdwI&feature=youtu.be

**Comment by xaphod** [comment]
Hi CJ,

Please see the gist here:
https://gist.github.com/xaphod/715863b1b9a6304adcf8119e83497314
If I change .rawBody to .body on line 11 as per your example, it fails. Am
running it on Firebase Emulator.
Package-lock attached for versions.
Please note, there is no middleware / any commands affecting express,
before this gist.

cheers,
Tim Carr
Founder, *Solodigitalis*
M: 289-237-1935
W: solodigitalis.com
A: 270 Sherman Ave N, Hamilton, ON L8L 6N4

**Comment by cjavilla-stripe** [comment]
I didn't see the attached package.json, but am wondering if this is a difference between the firebase emulator and running natively with node.

**Comment by xaphod** [comment]
If the firebase emulator was the issue, there would be a zillion other
issues all over the place. That's not the case, so it's highly unlikely to
be a firebase-only issue.
Attached the package-lock.json file again, this time zipped. Can you see it
now?
I'm guessing it is a version issue: your code expects something in
body-parser, or Node itself, that is different in a version i'm using. And
looking at the github issues, a lot of other people too.

Tim Carr
Founder, *Solodigitalis*
M: 289-237-1935
W: solodigitalis.com
A: 270 Sherman Ave N, Hamilton, ON L8L 6N4

**Comment by cjavilla-stripe** [comment]
I don't think Github is ingesting attachments in your email replies to the github issue, Tim. Can you add in a gist and I'll try to reproduce? Looking forward to getting to the bottom of this :)

**Comment by xaphod** [comment]
Ugh, sorry, I wasn't paying attention and hadn't noticed this was over github (I have other email threads open with Stripe and thought this was one of them).
File properly attached here.
[package-lock.json.zip](https://github.com/stripe/stripe-node/files/4476678/package-lock.json.zip)

**Comment by mitchellbutler** [comment]
For what it's worth, I've encountered this on Firebase Cloud Functions and [the StackOverflow issue](https://stackoverflow.com/questions/53899365/stripe-error-no-signatures-found-matching-the-expected-signature-for-payload) that lead me here was from a Firebase user as well.

@cjavilla-stripe is right that Firebase is doing its own parsing of body content in Express. Here it is [in their documentation](https://cloud.google.com/functions/docs/writing/http#parsing_http_requests):

> In Node.js, the body of the request is automatically parsed based on the content-type header and made available via your HTTP function's arguments.

If you're using Firebase Cloud Functions, you should already have access to the `req.rawBody` prop without the fixes above. [Here's an issue](https://github.com/firebase/firebase-functions/issues/417#issuecomment-467542103) where it's mentioned:

> While rawBody was removed from express a while ago, Cloud Functions still provides it.

If you're using TypeScript with GCF's default settings you won't be able to deploy because of a TS error like this:

```
Property 'rawBody' does not exist on type 'Request<ParamsDictionary, any, any>'.
```

Firebase provides its own types though and in this case I think you can safely assert the type like this:

```ts
import { https } from 'firebase-functions'

app.post('/', async (req, res) => {
  // ...
  const firebaseRequest = req as https.Request
  event = stripe.webhooks.constructEvent(
    firebaseRequest.rawBody,
    sig,
    ENDPOINT_SECRET,
  )
  // ...
}
```

This solved the issue for me.

**Comment by janswist** [comment]
> 
> ```ts
> import express from 'express'
> import { https } from 'firebase-functions'
> 
> const app = express()
> 
> app.post('/', async (req, res) => {
>   // ...
>   const firebaseRequest = req as https.Request
>   event = stripe.webhooks.constructEvent(
>     firebaseRequest.rawBody,
>     sig,
>     ENDPOINT_SECRET,
>   )
>   // ...
> }
> ```
> 
> This solved the issue for me.

This helped me solve the issue. There is no even need for `const firebaseRequest = req as https.Request`. You can just use `req.rawBody` instead of `firebaseRequest.rawBody` (at least for vanilla javascript). Thanks!

**Comment by jamesoflol** [comment]
> @mebibou No, the signature verification needs the raw body as a text string. Reserializing already deserialized JSON back into a text string doesn't work as the resulting string might be different (key order is not guaranteed, indentation might be different, etc.).

You (Stripe) control the both the creation of the original body buffer, and the node-stripe library. Would it be possible for you to write a function in the node-stripe library that reserialises a Javascript object into the expected string? By my understanding, you have all the knowledge of the expected key order and indentation. You'd need to roll your own serialising function, but it doesn't look insurmountable.

Or am I critically misunderstanding some element of the feasibility of this?

I appreciate that this is a common thing to read raw payloads in other languages/frameworks, but the whole point of an SDK is to make the lives of developers easier, and to fit into the ecosystem of that language. It looks to me that this issue trips up almost every single user of your SDK. Not only that, but this is a security issue for Stripe. I'll bet that for every dev who implements this properly, there's five others who just skip validating the signature, because it's too hard.

While I'm here, I just want to say that, despite this interesting hurdle, Stripe is an absolute pleasure to work with. I'm building a startup and have found the Stripe web interface, libraries, support, docs to be fantastic. Stripe-cli is awesome for testing webhooks! Thanks heaps and keep up the good work.

**Comment by remi-stripe** [comment]
@jamesoflol Thanks a lot for the thoughtful comment, we really appreciate it! This sparked some interesting conversations internally, and brought back again the topic around approaching event signature potentially differently in the future too to make it easier for developers.
This is especially problematic for stripe-node users which is where we get the vast majority of reports and issues. We don't have anything concrete yet but we are definitely looking into solutions!

**Comment by taimoorgit** [comment]
My adaptation of @kurry421's answer:

The webhook:
```
const router = require('express').Router()
const stripe = require('stripe')(process.env.STRIPE_SECRET)
const bodyParser = require('body-parser')

// https://stripe.com/docs/payments/checkout/fulfill-orders#fulfill
// Do not change responses, since there are standard from stripe
// NEED to use body parser, express.json for some reason is not compatible

router.post('/checkout_session_completed', async (req, res) => {
    const sig = req.headers['stripe-signature']
    const payload = req.body

    let event
    try {
        event = stripe.webhooks.constructEvent(payload, sig, process.env.STRIPE_ENDPOINT_SECRET)
    } catch (err) {
        return res.status(400).json(`Webhook Error: ${err.message}`)
    }

    // Handle the checkout.session.completed event
    if (event.type === 'checkout.session.completed') {
        const session = event.data.object

        // Fulfill the purchase...
        console.log(session)
    }

    res.sendStatus(200)
})

module.exports = router
```

My app.js:
```
const express = require('express')
const mongoose = require('mongoose')
const dotenv = require('dotenv')
const cors = require('cors')
const bodyParser = require('body-parser')

// Setup server
dotenv.config()
mongoose.set('useNewUrlParser', true)
mongoose.set('useFindAndModify', false)
mongoose.set('useCreateIndex', true)
mongoose.set('useUnifiedTopology', true)
mongoose.connect(process.env.MONGODB, { useNewUrlParser: true, useUnifiedTopology: true }, (err) => {
    if (err) {
        console.log(`MongoDB error: ${err}`)
    } else {
        console.log('Connected to MongoDB!')
    }
})
const app = express()
app.use(cors())
app.use('/webhooks/stripe', bodyParser.raw({ type: '*/*' }), require("./webhooks/stripe"))
app.use(express.json())

// API routes
app.use('/api/v1/auth', require('./auth/auth'))
app.use('/api/v1/images', require('./image/upload'))
app.use('/api/v1/images', require('./image/search'))
app.use('/api/v1/images', require('./image/search_related'))
app.use('/api/v1/images', require('./image/delete'))
app.use('/api/v1/images', require('./image/update'))
app.use('/api/v1/images', require('./image/view'))
app.use('/api/v1/marketplace', require('./marketplace/purchase'))
app.use('/api/v1/marketplace', require('./marketplace/coupons'))
app.use('/api/v1/marketplace', require('./marketplace/purchases'))

// Start server
let port = process.env.PORT
if (!port) {
    port = 5000
}
app.listen(port, () => {
    console.log(`Server started on ${port}!`)
})
```

A few things to keep in mind:
- Make sure to setup `cors()` first
- Setup `express.json()` (if you're using it) AFTER setting up the webhook route
- Actually SEND a status rather than just setting `res.status(200)`

**Comment by Aadmaa** [comment]
The **raw-body** package is an easy solution if you don't need **body-parser**. Then in your server setup you can just send the (req, res) tuple to your endpoint handler, as-is.

`app.post('/stripehooks', (req, res) => stripehooks(req, res))`

**In stripehooks:**
`import getRawBody from 'raw-body';`

[...]

```
const rawBody = await getRawBody(req);

try {
  event = stripe.webhooks.constructEvent(rawBody, sig, whSecret);
} catch (err) {
  return res.status(401).end(`Error validating webhook (test mode): ${err.message}`);
}
```

**Comment by shumiyao** [comment]
#### Works if you are:
* Using Express version: ^4.17.1
* Struggling with bodyParser deprecated problem.

#### My solution

Try the following lines before you start up your express server: 

```
const app = express();
const express = require('express');

...

app.use("/your/stripe/webhook/endpoint", express.raw({ type: "*/*" }));
app.use(express.json());

...
```
#### Notes:
* You will need to change "/your/stripe/webhook/endpoint" to your own.

**Comment by gieoon** [comment]
https://github.com/stripe/stripe-node/blob/master/examples/webhook-signing/node-express/express.js

**Comment by aneeshjoshi** [comment]
> For what it's worth, I've encountered this on Firebase Cloud Functions and [the StackOverflow issue](https://stackoverflow.com/questions/53899365/stripe-error-no-signatures-found-matching-the-expected-signature-for-payload) that lead me here was from a Firebase user as well.
> 
> @cjavilla-stripe is right that Firebase is doing its own parsing of body content in Express. Here it is [in their documentation](https://cloud.google.com/functions/docs/writing/http#parsing_http_requests):
> 
> > In Node.js, the body of the request is automatically parsed based on the content-type header and made available via your HTTP function's arguments.
> 
> If you're using Firebase Cloud Functions, you should already have access to the `req.rawBody` prop without the fixes above. [Here's an issue](https://github.com/firebase/firebase-functions/issues/417#issuecomment-467542103) where it's mentioned:
> 
> > While rawBody was removed from express a while ago, Cloud Functions still provides it.
> 
> If you're using TypeScript with GCF's default settings you won't be able to deploy because of a TS error like this:
> 
> ```
> Property 'rawBody' does not exist on type 'Request<ParamsDictionary, any, any>'.
> ```
> 
> Firebase provides its own types though and in this case I think you can safely assert the type like this:
> 
> ```ts
> import express from 'express'
> import { https } from 'firebase-functions'
> 
> const app = express()
> 
> app.post('/', async (req, res) => {
>   // ...
>   const firebaseRequest = req as https.Request
>   event = stripe.webhooks.constructEvent(
>     firebaseRequest.rawBody,
>     sig,
>     ENDPOINT_SECRET,
>   )
>   // ...
> }
> ```
> 
> This solved the issue for me.

This was a lifesaver on firebase cloud functions. Thanks @mitchellbutler.

**Comment by cgarrovillo** [comment]
> The above example has been added as an example https://github.com/stripe/stripe-node/blob/master/examples/webhook-signing/node-express/express.js

The example needs to be updated once again.

On Stripe 8.217.0 there is no longer a need for it to be a buffer.

**Comment by pencilcheck** [comment]
> 

Still doesn't work for me, still getting the same error.

**Comment by NithinSGowda** [comment]
Doesn't work in GCP App engine, it parses it into JSON same as firebase does, but `rawBody` isn't available as that of a firebase request.
Why can't the SDK accept a parsed JSON in `constructEvent`? Any specific security reason?

**Comment by iBobik** [comment]
> Why can't the SDK accept a parsed JSON in `constructEvent`? Any specific security reason?

Verification of signature requires to have the data exactly the same like it was on the signer's machine. This could be guaranteed on string or buffer, but unserialised object does not guarantee e.g. properties order.

**Comment by Snouzy** [comment]
Hey ! If you are on Typescript, here's a middleware that you can add to your route : 


```ts
interface RequestWithRawBody extends Request {
  rawBody: Buffer;
}

const addRawBody = () => (req: Stream, _: Response, next: NextFunction) => {
  const chunks: Buffer[] = [];

  req.on("data", (chunk: Buffer) => {
    chunks.push(chunk);
  });

  req.on("end", () => {
    ((req as unknown) as RequestWithRawBody).rawBody = Buffer.concat(chunks);
    next();
  });
};

```

**Comment by douglas-artoh** [comment]
hey friends if you are using the bodyParser in the app, the validation will not work.

`app.use(bodyParser.json());
`

replace with the code below
```
app.use(
   bodyParser.json({
     verify: function(req, res, buf) {
       req.rawBody = buf;
     }
   })
);
```
in the function to build the event pass the rawBody

`event = stripe.webhooks.constructEvent(req.rawBody, sig, endpointSecret);`

after this change here it worked

**Comment by russtack** [comment]
> hey friends if you are using the bodyParser in the app, the validation will not work.
> 
> `app.use(bodyParser.json()); `
> 
> replace with the code below
> 
> ```
> app.use(
>    bodyParser.json({
>      verify: function(req, res, buf) {
>        req.rawBody = buf;
>      }
>    })
> );
> ```
> 
> in the function to build the event pass the rawBody
> 
> `event = stripe.webhooks.constructEvent(req.rawBody, sig, endpointSecret);`
> 
> after this change here it worked

Many Many thanks Douglas, out of all solutions this one worked for me!

**Comment by yura0seredyuk** [comment]
using rawBody instead of body helps me
`event = stripe.webhooks.constructEvent(req.rawBody, sig, endpointSecret);`

**Comment by bajere** [comment]
> My adaptation of @kurry421's answer:
> 
> The webhook:
> 
> ```
> const router = require('express').Router()
> const stripe = require('stripe')(process.env.STRIPE_SECRET)
> const bodyParser = require('body-parser')
> 
> // https://stripe.com/docs/payments/checkout/fulfill-orders#fulfill
> // Do not change responses, since there are standard from stripe
> // NEED to use body parser, express.json for some reason is not compatible
> 
> router.post('/checkout_session_completed', async (req, res) => {
>     const sig = req.headers['stripe-signature']
>     const payload = req.body
> 
>     let event
>     try {
>         event = stripe.webhooks.constructEvent(payload, sig, process.env.STRIPE_ENDPOINT_SECRET)
>     } catch (err) {
>         return res.status(400).json(`Webhook Error: ${err.message}`)
>     }
> 
>     // Handle the checkout.session.completed event
>     if (event.type === 'checkout.session.completed') {
>         const session = event.data.object
> 
>         // Fulfill the purchase...
>         console.log(session)
>     }
> 
>     res.sendStatus(200)
> })
> 
> module.exports = router
> ```
> 
> My app.js:
> 
> ```
> const express = require('express')
> const mongoose = require('mongoose')
> const dotenv = require('dotenv')
> const cors = require('cors')
> const bodyParser = require('body-parser')
> 
> // Setup server
> dotenv.config()
> mongoose.set('useNewUrlParser', true)
> mongoose.set('useFindAndModify', false)
> mongoose.set('useCreateIndex', true)
> mongoose.set('useUnifiedTopology', true)
> mongoose.connect(process.env.MONGODB, { useNewUrlParser: true, useUnifiedTopology: true }, (err) => {
>     if (err) {
>         console.log(`MongoDB error: ${err}`)
>     } else {
>         console.log('Connected to MongoDB!')
>     }
> })
> const app = express()
> app.use(cors())
> app.use('/webhooks/stripe', bodyParser.raw({ type: '*/*' }), require("./webhooks/stripe"))
> app.use(express.json())
> 
> // API routes
> app.use('/api/v1/auth', require('./auth/auth'))
> app.use('/api/v1/images', require('./image/upload'))
> app.use('/api/v1/images', require('./image/search'))
> app.use('/api/v1/images', require('./image/search_related'))
> app.use('/api/v1/images', require('./image/delete'))
> app.use('/api/v1/images', require('./image/update'))
> app.use('/api/v1/images', require('./image/view'))
> app.use('/api/v1/marketplace', require('./marketplace/purchase'))
> app.use('/api/v1/marketplace', require('./marketplace/coupons'))
> app.use('/api/v1/marketplace', require('./marketplace/purchases'))
> 
> // Start server
> let port = process.env.PORT
> if (!port) {
>     port = 5000
> }
> app.listen(port, () => {
>     console.log(`Server started on ${port}!`)
> })
> ```
> 
> A few things to keep in mind:
> 
> * Make sure to setup `cors()` first
> * Setup `express.json()` (if you're using it) AFTER setting up the webhook route
> * Actually SEND a status rather than just setting `res.status(200)`

I just wasted half a day on this! Moving the express.json() to the bottom worked! Thanks

**Comment by fabriziospadaro** [comment]
That's how i solved it:

`app.use((req, res, next) => {
  if (req.originalUrl.includes('YOUR_STRIPE_WEBHOOK')) {
    next();
  } else {
    bodyParser.json()(req, res, next);
  }
});`

**Comment by Noushad-web** [comment]
I faced a similar issue and tried various approaches, including using body parser and exploring other options. Eventually, I discovered the Stripe GitHub examples repository, and its examples helped me resolve my issue.[link](https://github.com/stripe/stripe-node/blob/master/examples/webhook-signing/express/main.ts)

**Comment by TaseenRudra** [comment]
`app.use('/api/v1/stripe/webhook', bodyParser.raw({ type: 'application/json' }));`


add your specific url  on it

**Comment by michaelboeding** [comment]
I ran into this issue also while using Google Cloud Functions. The link here helped me fix it : https://stackoverflow.com/questions/53899365/stripe-error-no-signatures-found-matching-the-expected-signature-for-payload


1. Use req.rawBody
2. Make sure you are using the right webhook secret which is listed in the stripe console and is specific to each web hook.

**Comment by oleksii-pi** [comment]
I've killed half a day learning how it should work. My stack is Firebase, Express, TypeScript. I do not use any JSON parsing middleware, but `req.body` was always an object.

I ended up with this hack:

```typescript
// index.ts:
const app = express();
app.use(express.json({
  verify: (req, res, buf) => {
    (req as any).rawBody = buf; // <<
  }
}));
```

```typescript
// webhook.ts
export const webhook = async (req: Request, res: Response) => {
  const sig = req.headers["stripe-signature"];
  if (sig === undefined) {
    console.error("Stripe signature is missing.");
    res.status(400).send("Stripe signature is missing.");
    return;
  }

  const stripe = getStripeApi();
  const webhookSecret = STRIPE_WEBHOOK_SECRET_KEY.value();

  let event: Stripe.Event;
  try {
    event = stripe.webhooks.constructEvent(req.rawBody, sig, webhookSecret); // <<
  } catch (error) {
    console.error("Webhook signature verification failed.", error);
    res.status(400).send(`Webhook Error: ${(error as any).message}`);
    return;
  }
};
```

```typescript
// stripeapi.ts
import Stripe from "stripe";
import { defineSecret } from "firebase-functions/params";
export const STRIPE_SECRET_KEY = defineSecret("STRIPE_SECRET_KEY");

let stripeApi: Stripe | null = null;
export const getStripeApi = () => {
  return stripeApi ?? (stripeApi = new Stripe(STRIPE_SECRET_KEY.value(), { apiVersion: "2024-06-20" }));
};
```

```typescript
// express.d.ts
import { Request } from "express";

declare module "express-serve-static-core" {
  interface Request {
    rawBody: Buffer; // <<
  }
}
```

**Comment by alexstyl** [comment]
The simplest thing that worked for me is to move the stripe webhook before using `app.use(bodyParser.json()):

```javascript
const app = express();
app.use(cors())
app.post('/your-webhook-path', bodyParser.raw({type: '*/*'}), (request, response) => { 
    // the rest of the webhook
})
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));
```

**Comment by Fenil-Mansukhbhai-Vaghasiya** [comment]
Good one this is more optimized solution as compare to getting static url of stripe hook and adding it in if else bloakc to it, you can also use express.raw instead of bodyparser it will work same.

**Comment by Samuel01111** [comment]
@alexstyl This works for me, after 10 hours at least, thank you

**Comment by nelsonTK** [comment]
> app.use('/webhooks/stripe', bodyParser.raw({type: "*/*"}))


Well done, it was what was missing for me

**Comment by xnslx** [comment]
I am using React Router V7 framework mode with custom node backend, after trying all the previous solution, I happened to find this one that is working, 

```
...
    const payload = req.body;
    const payloadString = JSON.stringify(payload, null, 2);

    let event;

    try {
      event = stripe.webhooks.constructEvent(
        payloadString,
        sig!,
        process.env.STRIPE_WEBHOOK_SECRET!
      );
      console.log('✅ Event verified:', event.type);
    } catch (err: any) {
      console.error('❌ Webhook signature verification failed.', err.message);
      return res.status(400).send(`Webhook Error: ${err.message}`);
    }
...
```

**Comment by DaveKlassen** [comment]
> I am using React Router V7 framework mode with custom node backend, after trying all the previous solution, I happened to find this one that is working,

I like your solution, but what if Stripe changes the format, then technically this will break right?

I also like the middleware changes that provide for the rawBody field, to provide the original saved  data...
however we are adding some memory overhead in that solution to every incoming request...

I can't help thinking there must be a better way. I guess I will add the field only to requests related to the Stripe Webhook end point. That seems to be the least hacky of these hacky solutions
